# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 738)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("color:rgb(0, 0, 0)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.Inventory = QtWidgets.QWidget()
        self.Inventory.setStyleSheet("QPushButton:hover{\n"
"    border: none;\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Inventory.setObjectName("Inventory")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.Inventory)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.groupBox = QtWidgets.QGroupBox(self.Inventory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.inv_uploadSKU = QtWidgets.QPushButton(self.groupBox)
        self.inv_uploadSKU.setObjectName("inv_uploadSKU")
        self.gridLayout.addWidget(self.inv_uploadSKU, 0, 1, 1, 1)
        self.inv_dataProcess = QtWidgets.QPushButton(self.groupBox)
        self.inv_dataProcess.setObjectName("inv_dataProcess")
        self.gridLayout.addWidget(self.inv_dataProcess, 1, 0, 1, 1)
        self.inv_upload = QtWidgets.QPushButton(self.groupBox)
        self.inv_upload.setObjectName("inv_upload")
        self.gridLayout.addWidget(self.inv_upload, 0, 0, 1, 1)
        self.inv_inventoryAnalysis = QtWidgets.QPushButton(self.groupBox)
        self.inv_inventoryAnalysis.setObjectName("inv_inventoryAnalysis")
        self.gridLayout.addWidget(self.inv_inventoryAnalysis, 1, 1, 1, 1)
        self.inv_clear = QtWidgets.QPushButton(self.groupBox)
        self.inv_clear.setObjectName("inv_clear")
        self.gridLayout.addWidget(self.inv_clear, 2, 1, 1, 1)
        self.inv_download = QtWidgets.QPushButton(self.groupBox)
        self.inv_download.setObjectName("inv_download")
        self.gridLayout.addWidget(self.inv_download, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Inventory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.inv_dateCol = QtWidgets.QLineEdit(self.groupBox_2)
        self.inv_dateCol.setObjectName("inv_dateCol")
        self.gridLayout_2.addWidget(self.inv_dateCol, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 1)
        self.inv_putawayDateCol = QtWidgets.QLineEdit(self.groupBox_2)
        self.inv_putawayDateCol.setObjectName("inv_putawayDateCol")
        self.gridLayout_2.addWidget(self.inv_putawayDateCol, 1, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 1, 4, 1, 1)
        self.inv_customerCol = QtWidgets.QLineEdit(self.groupBox_2)
        self.inv_customerCol.setObjectName("inv_customerCol")
        self.gridLayout_2.addWidget(self.inv_customerCol, 1, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 6, 1, 1)
        self.inv_skuCol = QtWidgets.QLineEdit(self.groupBox_2)
        self.inv_skuCol.setObjectName("inv_skuCol")
        self.gridLayout_2.addWidget(self.inv_skuCol, 1, 7, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.inv_skuSizeCol = QtWidgets.QLineEdit(self.groupBox_2)
        self.inv_skuSizeCol.setObjectName("inv_skuSizeCol")
        self.gridLayout_2.addWidget(self.inv_skuSizeCol, 2, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_2)
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 2, 2, 1, 1)
        self.inv_invQty = QtWidgets.QLineEdit(self.groupBox_2)
        self.inv_invQty.setObjectName("inv_invQty")
        self.gridLayout_2.addWidget(self.inv_invQty, 2, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 2, 4, 1, 1)
        self.inv_invVol = QtWidgets.QLineEdit(self.groupBox_2)
        self.inv_invVol.setObjectName("inv_invVol")
        self.gridLayout_2.addWidget(self.inv_invVol, 2, 5, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.groupBox_2)
        self.label_66.setObjectName("label_66")
        self.gridLayout_2.addWidget(self.label_66, 2, 6, 1, 1)
        self.inv_locTypeCol = QtWidgets.QLineEdit(self.groupBox_2)
        self.inv_locTypeCol.setObjectName("inv_locTypeCol")
        self.gridLayout_2.addWidget(self.inv_locTypeCol, 2, 7, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.groupBox_2)
        self.label_60.setObjectName("label_60")
        self.gridLayout_2.addWidget(self.label_60, 3, 0, 1, 1)
        self.inv_skuLengthCol = QtWidgets.QLineEdit(self.groupBox_2)
        self.inv_skuLengthCol.setObjectName("inv_skuLengthCol")
        self.gridLayout_2.addWidget(self.inv_skuLengthCol, 3, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.groupBox_2)
        self.label_62.setObjectName("label_62")
        self.gridLayout_2.addWidget(self.label_62, 3, 2, 1, 1)
        self.inv_skuWidthCol = QtWidgets.QLineEdit(self.groupBox_2)
        self.inv_skuWidthCol.setObjectName("inv_skuWidthCol")
        self.gridLayout_2.addWidget(self.inv_skuWidthCol, 3, 3, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.groupBox_2)
        self.label_65.setObjectName("label_65")
        self.gridLayout_2.addWidget(self.label_65, 3, 4, 1, 1)
        self.inv_skuHeightCol = QtWidgets.QLineEdit(self.groupBox_2)
        self.inv_skuHeightCol.setObjectName("inv_skuHeightCol")
        self.gridLayout_2.addWidget(self.inv_skuHeightCol, 3, 5, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.groupBox_2)
        self.label_67.setObjectName("label_67")
        self.gridLayout_2.addWidget(self.label_67, 3, 6, 1, 1)
        self.inv_locNumCol = QtWidgets.QLineEdit(self.groupBox_2)
        self.inv_locNumCol.setObjectName("inv_locNumCol")
        self.gridLayout_2.addWidget(self.inv_locNumCol, 3, 7, 1, 1)
        self.input_hint = QtWidgets.QLabel(self.groupBox_2)
        self.input_hint.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_hint.sizePolicy().hasHeightForWidth())
        self.input_hint.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.input_hint.setFont(font)
        self.input_hint.setMouseTracking(True)
        self.input_hint.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.input_hint.setTextFormat(QtCore.Qt.RichText)
        self.input_hint.setScaledContents(False)
        self.input_hint.setObjectName("input_hint")
        self.gridLayout_2.addWidget(self.input_hint, 0, 0, 1, 8)
        self.gridLayout_24.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Inventory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.input_hint_2 = QtWidgets.QLabel(self.groupBox_3)
        self.input_hint_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_hint_2.sizePolicy().hasHeightForWidth())
        self.input_hint_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.input_hint_2.setFont(font)
        self.input_hint_2.setMouseTracking(True)
        self.input_hint_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.input_hint_2.setTextFormat(QtCore.Qt.RichText)
        self.input_hint_2.setScaledContents(False)
        self.input_hint_2.setObjectName("input_hint_2")
        self.gridLayout_6.addWidget(self.input_hint_2, 0, 0, 1, 3)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 1)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.skuLengthCol = QtWidgets.QLineEdit(self.groupBox_3)
        self.skuLengthCol.setObjectName("skuLengthCol")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.skuLengthCol)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.skuWidthCol = QtWidgets.QLineEdit(self.groupBox_3)
        self.skuWidthCol.setObjectName("skuWidthCol")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.skuWidthCol)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.skuHeightCol = QtWidgets.QLineEdit(self.groupBox_3)
        self.skuHeightCol.setObjectName("skuHeightCol")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.skuHeightCol)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.gridLayout_6.addLayout(self.formLayout_4, 1, 2, 2, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 2, 0, 1, 1)
        self.skuSizeCol = QtWidgets.QLineEdit(self.groupBox_3)
        self.skuSizeCol.setObjectName("skuSizeCol")
        self.gridLayout_6.addWidget(self.skuSizeCol, 2, 1, 1, 1)
        self.skuCol = QtWidgets.QLineEdit(self.groupBox_3)
        self.skuCol.setObjectName("skuCol")
        self.gridLayout_6.addWidget(self.skuCol, 1, 1, 1, 1)
        self.gridLayout_24.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.Inventory)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.input_hint_7 = QtWidgets.QLabel(self.groupBox_13)
        self.input_hint_7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_hint_7.sizePolicy().hasHeightForWidth())
        self.input_hint_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.input_hint_7.setFont(font)
        self.input_hint_7.setMouseTracking(True)
        self.input_hint_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.input_hint_7.setTextFormat(QtCore.Qt.RichText)
        self.input_hint_7.setScaledContents(False)
        self.input_hint_7.setObjectName("input_hint_7")
        self.gridLayout_5.addWidget(self.input_hint_7, 0, 0, 1, 1)
        self.inv_dateEdit = QtWidgets.QDateEdit(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inv_dateEdit.sizePolicy().hasHeightForWidth())
        self.inv_dateEdit.setSizePolicy(sizePolicy)
        self.inv_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.inv_dateEdit.setObjectName("inv_dateEdit")
        self.gridLayout_5.addWidget(self.inv_dateEdit, 1, 0, 1, 1)
        self.gridLayout_24.addWidget(self.groupBox_13, 0, 3, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.inv_errorRow = QtWidgets.QLineEdit(self.Inventory)
        self.inv_errorRow.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.inv_errorRow.setObjectName("inv_errorRow")
        self.gridLayout_19.addWidget(self.inv_errorRow, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Inventory)
        self.label_4.setObjectName("label_4")
        self.gridLayout_19.addWidget(self.label_4, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.Inventory)
        self.label.setObjectName("label")
        self.gridLayout_19.addWidget(self.label, 0, 0, 1, 1)
        self.inv_totalRow = QtWidgets.QLineEdit(self.Inventory)
        self.inv_totalRow.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.inv_totalRow.setObjectName("inv_totalRow")
        self.gridLayout_19.addWidget(self.inv_totalRow, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Inventory)
        self.label_2.setObjectName("label_2")
        self.gridLayout_19.addWidget(self.label_2, 0, 2, 1, 1)
        self.inv_validRow = QtWidgets.QLineEdit(self.Inventory)
        self.inv_validRow.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.inv_validRow.setObjectName("inv_validRow")
        self.gridLayout_19.addWidget(self.inv_validRow, 0, 7, 1, 1)
        self.inv_totalCol = QtWidgets.QLineEdit(self.Inventory)
        self.inv_totalCol.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.inv_totalCol.setObjectName("inv_totalCol")
        self.gridLayout_19.addWidget(self.inv_totalCol, 0, 3, 1, 1)
        self.inv_totalSKU = QtWidgets.QLineEdit(self.Inventory)
        self.inv_totalSKU.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.inv_totalSKU.setObjectName("inv_totalSKU")
        self.gridLayout_19.addWidget(self.inv_totalSKU, 0, 10, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.Inventory)
        self.label_6.setObjectName("label_6")
        self.gridLayout_19.addWidget(self.label_6, 0, 11, 1, 1)
        self.inv_totalDays = QtWidgets.QLineEdit(self.Inventory)
        self.inv_totalDays.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.inv_totalDays.setObjectName("inv_totalDays")
        self.gridLayout_19.addWidget(self.inv_totalDays, 0, 12, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.Inventory)
        self.label_5.setObjectName("label_5")
        self.gridLayout_19.addWidget(self.label_5, 0, 9, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.Inventory)
        self.label_3.setObjectName("label_3")
        self.gridLayout_19.addWidget(self.label_3, 0, 6, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_19, 1, 0, 1, 4)
        self.label_7 = QtWidgets.QLabel(self.Inventory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(7, 56, 125);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_7.setObjectName("label_7")
        self.gridLayout_24.addWidget(self.label_7, 2, 0, 1, 1)
        self.inv_tableView = QtWidgets.QTableView(self.Inventory)
        self.inv_tableView.setAlternatingRowColors(True)
        self.inv_tableView.setObjectName("inv_tableView")
        self.inv_tableView.horizontalHeader().setMinimumSectionSize(40)
        self.inv_tableView.verticalHeader().setDefaultSectionSize(40)
        self.inv_tableView.verticalHeader().setMinimumSectionSize(40)
        self.gridLayout_24.addWidget(self.inv_tableView, 3, 0, 1, 4)
        self.label_80 = QtWidgets.QLabel(self.Inventory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_80.sizePolicy().hasHeightForWidth())
        self.label_80.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_80.setFont(font)
        self.label_80.setStyleSheet("color: rgb(7, 56, 125);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_80.setObjectName("label_80")
        self.gridLayout_24.addWidget(self.label_80, 4, 0, 1, 1)
        self.sku_tableView = QtWidgets.QTableView(self.Inventory)
        self.sku_tableView.setAlternatingRowColors(True)
        self.sku_tableView.setObjectName("sku_tableView")
        self.sku_tableView.horizontalHeader().setMinimumSectionSize(40)
        self.sku_tableView.verticalHeader().setDefaultSectionSize(40)
        self.sku_tableView.verticalHeader().setMinimumSectionSize(40)
        self.gridLayout_24.addWidget(self.sku_tableView, 5, 0, 1, 4)
        self.gridLayout_24.setRowStretch(0, 4)
        self.gridLayout_24.setRowStretch(1, 1)
        self.gridLayout_24.setRowStretch(2, 1)
        self.gridLayout_24.setRowStretch(3, 7)
        self.gridLayout_24.setRowStretch(4, 1)
        self.gridLayout_24.setRowStretch(5, 7)
        self.tabWidget.addTab(self.Inventory, "")
        self.Outbound = QtWidgets.QWidget()
        self.Outbound.setStyleSheet("QPushButton:hover{\n"
"    border: none;\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Outbound.setObjectName("Outbound")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Outbound)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_9 = QtWidgets.QGroupBox(self.Outbound)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.ob_orderCol2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.ob_orderCol2.setObjectName("ob_orderCol2")
        self.gridLayout_13.addWidget(self.ob_orderCol2, 1, 1, 1, 1)
        self.input_hint_5 = QtWidgets.QLabel(self.groupBox_9)
        self.input_hint_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_hint_5.sizePolicy().hasHeightForWidth())
        self.input_hint_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.input_hint_5.setFont(font)
        self.input_hint_5.setMouseTracking(True)
        self.input_hint_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.input_hint_5.setTextFormat(QtCore.Qt.RichText)
        self.input_hint_5.setScaledContents(False)
        self.input_hint_5.setObjectName("input_hint_5")
        self.gridLayout_13.addWidget(self.input_hint_5, 0, 0, 1, 4)
        self.label_48 = QtWidgets.QLabel(self.groupBox_9)
        self.label_48.setObjectName("label_48")
        self.gridLayout_13.addWidget(self.label_48, 1, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.groupBox_9)
        self.label_59.setObjectName("label_59")
        self.gridLayout_13.addWidget(self.label_59, 2, 0, 1, 1)
        self.ob_timeInCol = QtWidgets.QLineEdit(self.groupBox_9)
        self.ob_timeInCol.setObjectName("ob_timeInCol")
        self.gridLayout_13.addWidget(self.ob_timeInCol, 2, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.groupBox_9)
        self.label_61.setObjectName("label_61")
        self.gridLayout_13.addWidget(self.label_61, 2, 2, 1, 1)
        self.ob_channelCol = QtWidgets.QLineEdit(self.groupBox_9)
        self.ob_channelCol.setObjectName("ob_channelCol")
        self.gridLayout_13.addWidget(self.ob_channelCol, 3, 3, 1, 1)
        self.ob_orderStructureCol = QtWidgets.QLineEdit(self.groupBox_9)
        self.ob_orderStructureCol.setObjectName("ob_orderStructureCol")
        self.gridLayout_13.addWidget(self.ob_orderStructureCol, 2, 3, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.groupBox_9)
        self.label_64.setObjectName("label_64")
        self.gridLayout_13.addWidget(self.label_64, 3, 2, 1, 1)
        self.ob_platformCol = QtWidgets.QLineEdit(self.groupBox_9)
        self.ob_platformCol.setObjectName("ob_platformCol")
        self.gridLayout_13.addWidget(self.ob_platformCol, 3, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.groupBox_9)
        self.label_63.setObjectName("label_63")
        self.gridLayout_13.addWidget(self.label_63, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_9, 0, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.Outbound)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_70 = QtWidgets.QLabel(self.groupBox_11)
        self.label_70.setObjectName("label_70")
        self.gridLayout_21.addWidget(self.label_70, 1, 0, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.groupBox_11)
        self.label_69.setObjectName("label_69")
        self.gridLayout_21.addWidget(self.label_69, 0, 0, 1, 1)
        self.ob_hourinCutoffHour = QtWidgets.QLineEdit(self.groupBox_11)
        self.ob_hourinCutoffHour.setObjectName("ob_hourinCutoffHour")
        self.gridLayout_21.addWidget(self.ob_hourinCutoffHour, 1, 1, 1, 1)
        self.ob_hourinDate = QtWidgets.QDateEdit(self.groupBox_11)
        self.ob_hourinDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.ob_hourinDate.setObjectName("ob_hourinDate")
        self.gridLayout_21.addWidget(self.ob_hourinDate, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_11, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Outbound)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.ob_dataProcess = QtWidgets.QPushButton(self.groupBox_4)
        self.ob_dataProcess.setObjectName("ob_dataProcess")
        self.gridLayout_8.addWidget(self.ob_dataProcess, 3, 0, 1, 1)
        self.ob_orderUpload = QtWidgets.QPushButton(self.groupBox_4)
        self.ob_orderUpload.setObjectName("ob_orderUpload")
        self.gridLayout_8.addWidget(self.ob_orderUpload, 1, 0, 1, 1)
        self.ob_orderTimeUpload = QtWidgets.QPushButton(self.groupBox_4)
        self.ob_orderTimeUpload.setObjectName("ob_orderTimeUpload")
        self.gridLayout_8.addWidget(self.ob_orderTimeUpload, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.Outbound)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 1, 0, 1, 1)
        self.ob_dateCol = QtWidgets.QLineEdit(self.groupBox_5)
        self.ob_dateCol.setObjectName("ob_dateCol")
        self.gridLayout_9.addWidget(self.ob_dateCol, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_9.addWidget(self.label_23, 1, 2, 1, 1)
        self.ob_orderCol = QtWidgets.QLineEdit(self.groupBox_5)
        self.ob_orderCol.setObjectName("ob_orderCol")
        self.gridLayout_9.addWidget(self.ob_orderCol, 1, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 2, 0, 1, 1)
        self.ob_skuCol = QtWidgets.QLineEdit(self.groupBox_5)
        self.ob_skuCol.setObjectName("ob_skuCol")
        self.gridLayout_9.addWidget(self.ob_skuCol, 2, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setObjectName("label_24")
        self.gridLayout_9.addWidget(self.label_24, 2, 4, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_5)
        self.label_42.setObjectName("label_42")
        self.gridLayout_9.addWidget(self.label_42, 2, 2, 1, 1)
        self.ob_skuSizeCol = QtWidgets.QLineEdit(self.groupBox_5)
        self.ob_skuSizeCol.setObjectName("ob_skuSizeCol")
        self.gridLayout_9.addWidget(self.ob_skuSizeCol, 2, 3, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_5)
        self.label_43.setObjectName("label_43")
        self.gridLayout_9.addWidget(self.label_43, 1, 4, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_5)
        self.label_44.setObjectName("label_44")
        self.gridLayout_9.addWidget(self.label_44, 3, 0, 1, 1)
        self.ob_putawayDateCol = QtWidgets.QLineEdit(self.groupBox_5)
        self.ob_putawayDateCol.setObjectName("ob_putawayDateCol")
        self.gridLayout_9.addWidget(self.ob_putawayDateCol, 3, 1, 1, 1)
        self.ob_qtyCol = QtWidgets.QLineEdit(self.groupBox_5)
        self.ob_qtyCol.setObjectName("ob_qtyCol")
        self.gridLayout_9.addWidget(self.ob_qtyCol, 2, 5, 1, 1)
        self.ob_orderTagCol = QtWidgets.QLineEdit(self.groupBox_5)
        self.ob_orderTagCol.setObjectName("ob_orderTagCol")
        self.gridLayout_9.addWidget(self.ob_orderTagCol, 1, 5, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_5)
        self.label_45.setObjectName("label_45")
        self.gridLayout_9.addWidget(self.label_45, 3, 2, 1, 1)
        self.ob_pickupNoCol = QtWidgets.QLineEdit(self.groupBox_5)
        self.ob_pickupNoCol.setObjectName("ob_pickupNoCol")
        self.gridLayout_9.addWidget(self.ob_pickupNoCol, 3, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_5)
        self.label_46.setObjectName("label_46")
        self.gridLayout_9.addWidget(self.label_46, 3, 4, 1, 1)
        self.ob_locationCol = QtWidgets.QLineEdit(self.groupBox_5)
        self.ob_locationCol.setObjectName("ob_locationCol")
        self.gridLayout_9.addWidget(self.ob_locationCol, 3, 5, 1, 1)
        self.input_hint_3 = QtWidgets.QLabel(self.groupBox_5)
        self.input_hint_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_hint_3.sizePolicy().hasHeightForWidth())
        self.input_hint_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.input_hint_3.setFont(font)
        self.input_hint_3.setMouseTracking(True)
        self.input_hint_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.input_hint_3.setTextFormat(QtCore.Qt.RichText)
        self.input_hint_3.setScaledContents(False)
        self.input_hint_3.setObjectName("input_hint_3")
        self.gridLayout_9.addWidget(self.input_hint_3, 0, 0, 1, 6)
        self.gridLayout_3.addWidget(self.groupBox_5, 0, 2, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.Outbound)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.ob_platformAnalysis = QtWidgets.QPushButton(self.groupBox_7)
        self.ob_platformAnalysis.setObjectName("ob_platformAnalysis")
        self.gridLayout_12.addWidget(self.ob_platformAnalysis, 2, 1, 1, 1)
        self.ob_downloadAll = QtWidgets.QPushButton(self.groupBox_7)
        self.ob_downloadAll.setObjectName("ob_downloadAll")
        self.gridLayout_12.addWidget(self.ob_downloadAll, 2, 3, 1, 1)
        self.ob_clearAll = QtWidgets.QPushButton(self.groupBox_7)
        self.ob_clearAll.setObjectName("ob_clearAll")
        self.gridLayout_12.addWidget(self.ob_clearAll, 2, 4, 1, 1)
        self.ob_EIQanalysis = QtWidgets.QPushButton(self.groupBox_7)
        self.ob_EIQanalysis.setStyleSheet("")
        self.ob_EIQanalysis.setObjectName("ob_EIQanalysis")
        self.gridLayout_12.addWidget(self.ob_EIQanalysis, 0, 0, 1, 1)
        self.ob_skuSale = QtWidgets.QPushButton(self.groupBox_7)
        self.ob_skuSale.setObjectName("ob_skuSale")
        self.gridLayout_12.addWidget(self.ob_skuSale, 0, 4, 1, 1)
        self.ob_customerSale = QtWidgets.QPushButton(self.groupBox_7)
        self.ob_customerSale.setObjectName("ob_customerSale")
        self.gridLayout_12.addWidget(self.ob_customerSale, 0, 3, 1, 1)
        self.ob_multiOrder = QtWidgets.QPushButton(self.groupBox_7)
        self.ob_multiOrder.setObjectName("ob_multiOrder")
        self.gridLayout_12.addWidget(self.ob_multiOrder, 0, 1, 1, 1)
        self.ob_channelAnalysis = QtWidgets.QPushButton(self.groupBox_7)
        self.ob_channelAnalysis.setObjectName("ob_channelAnalysis")
        self.gridLayout_12.addWidget(self.ob_channelAnalysis, 2, 0, 1, 1)
        self.ob_skuHourIn = QtWidgets.QPushButton(self.groupBox_7)
        self.ob_skuHourIn.setObjectName("ob_skuHourIn")
        self.gridLayout_12.addWidget(self.ob_skuHourIn, 1, 0, 1, 1)
        self.ob_ABCanalysis = QtWidgets.QPushButton(self.groupBox_7)
        self.ob_ABCanalysis.setObjectName("ob_ABCanalysis")
        self.gridLayout_12.addWidget(self.ob_ABCanalysis, 1, 1, 1, 1)
        self.ob_orderAge = QtWidgets.QPushButton(self.groupBox_7)
        self.ob_orderAge.setObjectName("ob_orderAge")
        self.gridLayout_12.addWidget(self.ob_orderAge, 1, 4, 1, 1)
        self.ob_skuAge = QtWidgets.QPushButton(self.groupBox_7)
        self.ob_skuAge.setObjectName("ob_skuAge")
        self.gridLayout_12.addWidget(self.ob_skuAge, 1, 3, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_7, 2, 2, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.Outbound)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.ob_ABCfreq = QtWidgets.QLineEdit(self.groupBox_6)
        self.ob_ABCfreq.setObjectName("ob_ABCfreq")
        self.gridLayout_11.addWidget(self.ob_ABCfreq, 3, 1, 1, 1)
        self.input_hint_4 = QtWidgets.QLabel(self.groupBox_6)
        self.input_hint_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_hint_4.sizePolicy().hasHeightForWidth())
        self.input_hint_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.input_hint_4.setFont(font)
        self.input_hint_4.setMouseTracking(True)
        self.input_hint_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.input_hint_4.setTextFormat(QtCore.Qt.RichText)
        self.input_hint_4.setScaledContents(False)
        self.input_hint_4.setObjectName("input_hint_4")
        self.gridLayout_11.addWidget(self.input_hint_4, 1, 0, 1, 2)
        self.label_34 = QtWidgets.QLabel(self.groupBox_6)
        self.label_34.setObjectName("label_34")
        self.gridLayout_11.addWidget(self.label_34, 2, 0, 1, 1)
        self.ob_ABCintervalDays = QtWidgets.QLineEdit(self.groupBox_6)
        self.ob_ABCintervalDays.setObjectName("ob_ABCintervalDays")
        self.gridLayout_11.addWidget(self.ob_ABCintervalDays, 4, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        self.label_35.setObjectName("label_35")
        self.gridLayout_11.addWidget(self.label_35, 3, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_6)
        self.label_27.setObjectName("label_27")
        self.gridLayout_11.addWidget(self.label_27, 4, 0, 1, 1)
        self.ob_ABCparameter = QtWidgets.QLineEdit(self.groupBox_6)
        self.ob_ABCparameter.setObjectName("ob_ABCparameter")
        self.gridLayout_11.addWidget(self.ob_ABCparameter, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_6)
        self.line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.gridLayout_11.addWidget(self.line, 0, 2, 5, 1)
        self.ob_endDate = QtWidgets.QDateEdit(self.groupBox_6)
        self.ob_endDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 3, 31), QtCore.QTime(0, 0, 0)))
        self.ob_endDate.setObjectName("ob_endDate")
        self.gridLayout_11.addWidget(self.ob_endDate, 4, 3, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox_6)
        self.label_72.setTextFormat(QtCore.Qt.RichText)
        self.label_72.setObjectName("label_72")
        self.gridLayout_11.addWidget(self.label_72, 3, 3, 1, 1)
        self.ob_startDate = QtWidgets.QDateEdit(self.groupBox_6)
        self.ob_startDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.ob_startDate.setObjectName("ob_startDate")
        self.gridLayout_11.addWidget(self.ob_startDate, 2, 3, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.groupBox_6)
        self.label_71.setTextFormat(QtCore.Qt.AutoText)
        self.label_71.setObjectName("label_71")
        self.gridLayout_11.addWidget(self.label_71, 1, 3, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_6, 2, 1, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.ob_totalRow = QtWidgets.QLineEdit(self.Outbound)
        self.ob_totalRow.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";\n"
"")
        self.ob_totalRow.setObjectName("ob_totalRow")
        self.gridLayout_10.addWidget(self.ob_totalRow, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.Outbound)
        self.label_31.setMaximumSize(QtCore.QSize(60, 20))
        self.label_31.setObjectName("label_31")
        self.gridLayout_10.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.Outbound)
        self.label_29.setObjectName("label_29")
        self.gridLayout_10.addWidget(self.label_29, 0, 2, 1, 1)
        self.ob_errorRow = QtWidgets.QLineEdit(self.Outbound)
        self.ob_errorRow.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.ob_errorRow.setObjectName("ob_errorRow")
        self.gridLayout_10.addWidget(self.ob_errorRow, 0, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.Outbound)
        self.label_32.setObjectName("label_32")
        self.gridLayout_10.addWidget(self.label_32, 0, 10, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.Outbound)
        self.label_28.setObjectName("label_28")
        self.gridLayout_10.addWidget(self.label_28, 0, 8, 1, 1)
        self.ob_validRow = QtWidgets.QLineEdit(self.Outbound)
        self.ob_validRow.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.ob_validRow.setObjectName("ob_validRow")
        self.gridLayout_10.addWidget(self.ob_validRow, 0, 9, 1, 1)
        self.ob_totalSKU = QtWidgets.QLineEdit(self.Outbound)
        self.ob_totalSKU.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.ob_totalSKU.setObjectName("ob_totalSKU")
        self.gridLayout_10.addWidget(self.ob_totalSKU, 0, 13, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.Outbound)
        self.label_25.setObjectName("label_25")
        self.gridLayout_10.addWidget(self.label_25, 0, 12, 1, 1)
        self.ob_totalDays = QtWidgets.QLineEdit(self.Outbound)
        self.ob_totalDays.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.ob_totalDays.setObjectName("ob_totalDays")
        self.gridLayout_10.addWidget(self.ob_totalDays, 0, 15, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.Outbound)
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 0, 14, 1, 1)
        self.ob_totalOrders = QtWidgets.QLineEdit(self.Outbound)
        self.ob_totalOrders.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.ob_totalOrders.setObjectName("ob_totalOrders")
        self.gridLayout_10.addWidget(self.ob_totalOrders, 0, 11, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_10, 1, 0, 1, 3)
        self.ob_tableView = QtWidgets.QTableView(self.Outbound)
        self.ob_tableView.setStyleSheet("")
        self.ob_tableView.setAlternatingRowColors(True)
        self.ob_tableView.setObjectName("ob_tableView")
        self.ob_tableView.horizontalHeader().setCascadingSectionResizes(False)
        self.ob_tableView.horizontalHeader().setMinimumSectionSize(40)
        self.ob_tableView.verticalHeader().setDefaultSectionSize(40)
        self.ob_tableView.verticalHeader().setMinimumSectionSize(40)
        self.gridLayout_3.addWidget(self.ob_tableView, 4, 0, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.Outbound)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(7, 56, 125);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 3)
        self.label_68 = QtWidgets.QLabel(self.Outbound)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_68.sizePolicy().hasHeightForWidth())
        self.label_68.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_68.setFont(font)
        self.label_68.setStyleSheet("color: rgb(7, 56, 125);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_68.setObjectName("label_68")
        self.gridLayout_3.addWidget(self.label_68, 5, 0, 1, 3)
        self.ob_timeTableView = QtWidgets.QTableView(self.Outbound)
        self.ob_timeTableView.setStyleSheet("")
        self.ob_timeTableView.setAlternatingRowColors(True)
        self.ob_timeTableView.setObjectName("ob_timeTableView")
        self.ob_timeTableView.horizontalHeader().setMinimumSectionSize(40)
        self.ob_timeTableView.verticalHeader().setDefaultSectionSize(40)
        self.ob_timeTableView.verticalHeader().setMinimumSectionSize(40)
        self.gridLayout_3.addWidget(self.ob_timeTableView, 8, 0, 1, 2)
        self.textBrowser = QtWidgets.QTextBrowser(self.Outbound)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 8, 2, 1, 1)
        self.tabWidget.addTab(self.Outbound, "")
        self.Inbound = QtWidgets.QWidget()
        self.Inbound.setStyleSheet("QPushButton:hover{\n"
"    border: none;\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.Inbound.setObjectName("Inbound")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.Inbound)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.groupBox_8 = QtWidgets.QGroupBox(self.Inbound)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.ib_upload = QtWidgets.QPushButton(self.groupBox_8)
        self.ib_upload.setObjectName("ib_upload")
        self.gridLayout_15.addWidget(self.ib_upload, 0, 0, 1, 1)
        self.ib_dataProcess = QtWidgets.QPushButton(self.groupBox_8)
        self.ib_dataProcess.setObjectName("ib_dataProcess")
        self.gridLayout_15.addWidget(self.ib_dataProcess, 0, 1, 1, 1)
        self.ib_clear = QtWidgets.QPushButton(self.groupBox_8)
        self.ib_clear.setObjectName("ib_clear")
        self.gridLayout_15.addWidget(self.ib_clear, 4, 1, 1, 1)
        self.ib_download = QtWidgets.QPushButton(self.groupBox_8)
        self.ib_download.setObjectName("ib_download")
        self.gridLayout_15.addWidget(self.ib_download, 4, 0, 1, 1)
        self.ib_inboundAnalysis = QtWidgets.QPushButton(self.groupBox_8)
        self.ib_inboundAnalysis.setObjectName("ib_inboundAnalysis")
        self.gridLayout_15.addWidget(self.ib_inboundAnalysis, 2, 0, 1, 1)
        self.ib_cartonDistribution = QtWidgets.QPushButton(self.groupBox_8)
        self.ib_cartonDistribution.setObjectName("ib_cartonDistribution")
        self.gridLayout_15.addWidget(self.ib_cartonDistribution, 2, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.Inbound)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_76 = QtWidgets.QLabel(self.groupBox_12)
        self.label_76.setObjectName("label_76")
        self.gridLayout_17.addWidget(self.label_76, 2, 0, 1, 1)
        self.ib_startDate = QtWidgets.QDateEdit(self.groupBox_12)
        self.ib_startDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.ib_startDate.setObjectName("ib_startDate")
        self.gridLayout_17.addWidget(self.ib_startDate, 2, 1, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.groupBox_12)
        self.label_77.setObjectName("label_77")
        self.gridLayout_17.addWidget(self.label_77, 3, 0, 1, 1)
        self.ib_endDate = QtWidgets.QDateEdit(self.groupBox_12)
        self.ib_endDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 2, 1), QtCore.QTime(0, 0, 0)))
        self.ib_endDate.setObjectName("ib_endDate")
        self.gridLayout_17.addWidget(self.ib_endDate, 3, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_78.sizePolicy().hasHeightForWidth())
        self.label_78.setSizePolicy(sizePolicy)
        self.label_78.setObjectName("label_78")
        self.gridLayout_17.addWidget(self.label_78, 1, 0, 1, 2)
        self.gridLayout_23.addWidget(self.groupBox_12, 0, 1, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.Inbound)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.ib_inboundTypeCol = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_inboundTypeCol.setObjectName("ib_inboundTypeCol")
        self.gridLayout_16.addWidget(self.ib_inboundTypeCol, 1, 7, 1, 1)
        self.ib_inboundIdCol = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_inboundIdCol.setObjectName("ib_inboundIdCol")
        self.gridLayout_16.addWidget(self.ib_inboundIdCol, 1, 5, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBox_10)
        self.label_49.setObjectName("label_49")
        self.gridLayout_16.addWidget(self.label_49, 1, 4, 1, 1)
        self.label_ib_receive_time = QtWidgets.QLabel(self.groupBox_10)
        self.label_ib_receive_time.setObjectName("label_ib_receive_time")
        self.gridLayout_16.addWidget(self.label_ib_receive_time, 1, 2, 1, 1)
        self.ib_receiveTimeCol = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_receiveTimeCol.setObjectName("ib_receiveTimeCol")
        self.gridLayout_16.addWidget(self.ib_receiveTimeCol, 1, 3, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.groupBox_10)
        self.label_54.setObjectName("label_54")
        self.gridLayout_16.addWidget(self.label_54, 2, 2, 1, 1)
        self.ib_containerNoCol = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_containerNoCol.setObjectName("ib_containerNoCol")
        self.gridLayout_16.addWidget(self.ib_containerNoCol, 2, 3, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.groupBox_10)
        self.label_51.setObjectName("label_51")
        self.gridLayout_16.addWidget(self.label_51, 2, 4, 1, 1)
        self.ib_trackingNO = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_trackingNO.setObjectName("ib_trackingNO")
        self.gridLayout_16.addWidget(self.ib_trackingNO, 2, 5, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.groupBox_10)
        self.label_74.setObjectName("label_74")
        self.gridLayout_16.addWidget(self.label_74, 2, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.groupBox_10)
        self.label_53.setObjectName("label_53")
        self.gridLayout_16.addWidget(self.label_53, 1, 6, 1, 1)
        self.label_ib_date = QtWidgets.QLabel(self.groupBox_10)
        self.label_ib_date.setObjectName("label_ib_date")
        self.gridLayout_16.addWidget(self.label_ib_date, 1, 0, 1, 1)
        self.ib_customerCol = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_customerCol.setObjectName("ib_customerCol")
        self.gridLayout_16.addWidget(self.ib_customerCol, 3, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.groupBox_10)
        self.label_50.setObjectName("label_50")
        self.gridLayout_16.addWidget(self.label_50, 3, 2, 1, 1)
        self.ib_dateCol = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_dateCol.setObjectName("ib_dateCol")
        self.gridLayout_16.addWidget(self.ib_dateCol, 1, 1, 1, 1)
        self.ib_deliveryModeCol = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_deliveryModeCol.setObjectName("ib_deliveryModeCol")
        self.gridLayout_16.addWidget(self.ib_deliveryModeCol, 2, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_10)
        self.label_52.setObjectName("label_52")
        self.gridLayout_16.addWidget(self.label_52, 2, 6, 1, 1)
        self.ib_warehouseCodeCol = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_warehouseCodeCol.setObjectName("ib_warehouseCodeCol")
        self.gridLayout_16.addWidget(self.ib_warehouseCodeCol, 3, 1, 1, 1)
        self.ib_cartonNoCol = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_cartonNoCol.setObjectName("ib_cartonNoCol")
        self.gridLayout_16.addWidget(self.ib_cartonNoCol, 2, 7, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.groupBox_10)
        self.label_75.setObjectName("label_75")
        self.gridLayout_16.addWidget(self.label_75, 3, 0, 1, 1)
        self.ib_skuSizeCol = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_skuSizeCol.setObjectName("ib_skuSizeCol")
        self.gridLayout_16.addWidget(self.ib_skuSizeCol, 3, 7, 1, 1)
        self.ib_skuCol = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_skuCol.setObjectName("ib_skuCol")
        self.gridLayout_16.addWidget(self.ib_skuCol, 3, 5, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.groupBox_10)
        self.label_56.setObjectName("label_56")
        self.gridLayout_16.addWidget(self.label_56, 3, 6, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.groupBox_10)
        self.label_55.setObjectName("label_55")
        self.gridLayout_16.addWidget(self.label_55, 3, 4, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.groupBox_10)
        self.label_57.setObjectName("label_57")
        self.gridLayout_16.addWidget(self.label_57, 1, 8, 1, 1)
        self.ib_quantityCol = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_quantityCol.setObjectName("ib_quantityCol")
        self.gridLayout_16.addWidget(self.ib_quantityCol, 1, 9, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.groupBox_10)
        self.label_58.setObjectName("label_58")
        self.gridLayout_16.addWidget(self.label_58, 2, 8, 1, 1)
        self.ib_volCol = QtWidgets.QLineEdit(self.groupBox_10)
        self.ib_volCol.setObjectName("ib_volCol")
        self.gridLayout_16.addWidget(self.ib_volCol, 2, 9, 1, 1)
        self.input_hint_6 = QtWidgets.QLabel(self.groupBox_10)
        self.input_hint_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_hint_6.sizePolicy().hasHeightForWidth())
        self.input_hint_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.input_hint_6.setFont(font)
        self.input_hint_6.setMouseTracking(True)
        self.input_hint_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.input_hint_6.setTextFormat(QtCore.Qt.RichText)
        self.input_hint_6.setScaledContents(False)
        self.input_hint_6.setObjectName("input_hint_6")
        self.gridLayout_16.addWidget(self.input_hint_6, 0, 0, 1, 10)
        self.gridLayout_23.addWidget(self.groupBox_10, 0, 2, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.ib_totalSKU = QtWidgets.QLineEdit(self.Inbound)
        self.ib_totalSKU.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.ib_totalSKU.setObjectName("ib_totalSKU")
        self.gridLayout_22.addWidget(self.ib_totalSKU, 0, 9, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.Inbound)
        self.label_39.setObjectName("label_39")
        self.gridLayout_22.addWidget(self.label_39, 0, 10, 1, 1)
        self.ib_totalRow = QtWidgets.QLineEdit(self.Inbound)
        self.ib_totalRow.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.ib_totalRow.setObjectName("ib_totalRow")
        self.gridLayout_22.addWidget(self.ib_totalRow, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.Inbound)
        self.label_20.setObjectName("label_20")
        self.gridLayout_22.addWidget(self.label_20, 0, 0, 1, 1)
        self.ib_validRow = QtWidgets.QLineEdit(self.Inbound)
        self.ib_validRow.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.ib_validRow.setObjectName("ib_validRow")
        self.gridLayout_22.addWidget(self.ib_validRow, 0, 7, 1, 1)
        self.ib_errorRow = QtWidgets.QLineEdit(self.Inbound)
        self.ib_errorRow.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.ib_errorRow.setObjectName("ib_errorRow")
        self.gridLayout_22.addWidget(self.ib_errorRow, 0, 5, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.Inbound)
        self.label_37.setObjectName("label_37")
        self.gridLayout_22.addWidget(self.label_37, 0, 4, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.Inbound)
        self.label_38.setObjectName("label_38")
        self.gridLayout_22.addWidget(self.label_38, 0, 8, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.Inbound)
        self.label_36.setObjectName("label_36")
        self.gridLayout_22.addWidget(self.label_36, 0, 6, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.Inbound)
        self.label_33.setObjectName("label_33")
        self.gridLayout_22.addWidget(self.label_33, 0, 2, 1, 1)
        self.ib_totalCol = QtWidgets.QLineEdit(self.Inbound)
        self.ib_totalCol.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.ib_totalCol.setObjectName("ib_totalCol")
        self.gridLayout_22.addWidget(self.ib_totalCol, 0, 3, 1, 1)
        self.ib_totalDays = QtWidgets.QLineEdit(self.Inbound)
        self.ib_totalDays.setStyleSheet("color: rgb(238, 115, 32);\n"
"font: 75 10pt \"Times New Roman\";")
        self.ib_totalDays.setObjectName("ib_totalDays")
        self.gridLayout_22.addWidget(self.ib_totalDays, 0, 11, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_22, 1, 0, 1, 3)
        self.label_40 = QtWidgets.QLabel(self.Inbound)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: rgb(7, 56, 125);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_40.setObjectName("label_40")
        self.gridLayout_23.addWidget(self.label_40, 2, 0, 1, 1)
        self.ib_dataTableView = QtWidgets.QTableView(self.Inbound)
        self.ib_dataTableView.setAlternatingRowColors(True)
        self.ib_dataTableView.setObjectName("ib_dataTableView")
        self.ib_dataTableView.horizontalHeader().setMinimumSectionSize(40)
        self.ib_dataTableView.verticalHeader().setDefaultSectionSize(40)
        self.ib_dataTableView.verticalHeader().setMinimumSectionSize(40)
        self.gridLayout_23.addWidget(self.ib_dataTableView, 3, 0, 1, 3)
        self.label_73 = QtWidgets.QLabel(self.Inbound)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("color: rgb(7, 56, 125);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_73.setObjectName("label_73")
        self.gridLayout_23.addWidget(self.label_73, 4, 0, 1, 1)
        self.ib_resultsTableView = QtWidgets.QTableView(self.Inbound)
        self.ib_resultsTableView.setAlternatingRowColors(True)
        self.ib_resultsTableView.setObjectName("ib_resultsTableView")
        self.ib_resultsTableView.horizontalHeader().setMinimumSectionSize(40)
        self.ib_resultsTableView.verticalHeader().setDefaultSectionSize(40)
        self.ib_resultsTableView.verticalHeader().setMinimumSectionSize(40)
        self.gridLayout_23.addWidget(self.ib_resultsTableView, 5, 0, 1, 3)
        self.gridLayout_23.setRowStretch(0, 4)
        self.gridLayout_23.setRowStretch(1, 1)
        self.gridLayout_23.setRowStretch(2, 1)
        self.gridLayout_23.setRowStretch(3, 7)
        self.gridLayout_23.setRowStretch(4, 1)
        self.gridLayout_23.setRowStretch(5, 7)
        self.tabWidget.addTab(self.Inbound, "")
        self.gridLayout_18.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "数据操作"))
        self.inv_uploadSKU.setText(_translate("MainWindow", "SKU数据导入"))
        self.inv_dataProcess.setText(_translate("MainWindow", "数据处理"))
        self.inv_upload.setText(_translate("MainWindow", "库存数据导入"))
        self.inv_inventoryAnalysis.setText(_translate("MainWindow", "库存分析"))
        self.inv_clear.setText(_translate("MainWindow", "清理重置"))
        self.inv_download.setText(_translate("MainWindow", "数据导出"))
        self.groupBox_2.setTitle(_translate("MainWindow", "库存数据设置"))
        self.label_9.setText(_translate("MainWindow", "库存日期"))
        self.inv_dateCol.setText(_translate("MainWindow", "14"))
        self.label_10.setText(_translate("MainWindow", "上架日期"))
        self.inv_putawayDateCol.setText(_translate("MainWindow", "3"))
        self.label_19.setText(_translate("MainWindow", "客户代码"))
        self.inv_customerCol.setText(_translate("MainWindow", "10"))
        self.label_11.setText(_translate("MainWindow", "产品代码"))
        self.inv_skuCol.setText(_translate("MainWindow", "5"))
        self.label_12.setText(_translate("MainWindow", "产品货型"))
        self.inv_skuSizeCol.setText(_translate("MainWindow", "6"))
        self.label_47.setText(_translate("MainWindow", "在库件数"))
        self.inv_invQty.setText(_translate("MainWindow", "25"))
        self.label_30.setText(_translate("MainWindow", "在库体积"))
        self.inv_invVol.setText(_translate("MainWindow", "26"))
        self.label_66.setText(_translate("MainWindow", "储位类型"))
        self.inv_locTypeCol.setText(_translate("MainWindow", "7"))
        self.label_60.setText(_translate("MainWindow", "产品长"))
        self.inv_skuLengthCol.setText(_translate("MainWindow", "21"))
        self.label_62.setText(_translate("MainWindow", "产品宽"))
        self.inv_skuWidthCol.setText(_translate("MainWindow", "22"))
        self.label_65.setText(_translate("MainWindow", "产品高"))
        self.inv_skuHeightCol.setText(_translate("MainWindow", "23"))
        self.label_67.setText(_translate("MainWindow", "库位数量"))
        self.inv_locNumCol.setText(_translate("MainWindow", "29"))
        self.input_hint.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#ff0000;\">填写导入数据对应的列编号(从0开始）</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "SKU数据设置"))
        self.input_hint_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#ff0000;\">填写列编号(从0开始）</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "产品代码"))
        self.skuLengthCol.setText(_translate("MainWindow", "2"))
        self.label_17.setText(_translate("MainWindow", "宽"))
        self.skuWidthCol.setText(_translate("MainWindow", "3"))
        self.label_18.setText(_translate("MainWindow", "高"))
        self.skuHeightCol.setText(_translate("MainWindow", "4"))
        self.label_16.setText(_translate("MainWindow", "长"))
        self.label_15.setText(_translate("MainWindow", "产品货型"))
        self.skuSizeCol.setText(_translate("MainWindow", "1"))
        self.skuCol.setText(_translate("MainWindow", "0"))
        self.groupBox_13.setTitle(_translate("MainWindow", "日期设置"))
        self.input_hint_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#000000;\">库存分析日期</span></p></body></html>"))
        self.inv_errorRow.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "异常数据行数"))
        self.label.setText(_translate("MainWindow", "数据总行数"))
        self.inv_totalRow.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "数据总列数"))
        self.inv_validRow.setText(_translate("MainWindow", "0"))
        self.inv_totalCol.setText(_translate("MainWindow", "0"))
        self.inv_totalSKU.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "总天数"))
        self.inv_totalDays.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "总SKU数"))
        self.label_3.setText(_translate("MainWindow", "有效数据总行数"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#07387d;\">数据源预览</span></p></body></html>"))
        self.label_80.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#07387d;\">结果预览</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Inventory), _translate("MainWindow", "库存分析"))
        self.groupBox_9.setTitle(_translate("MainWindow", "出库时间参数设置"))
        self.ob_orderCol2.setText(_translate("MainWindow", "7"))
        self.input_hint_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#ff0000;\">填写导入数据对应的列编号(从0开始）</span></p></body></html>"))
        self.label_48.setText(_translate("MainWindow", "*订单号"))
        self.label_59.setText(_translate("MainWindow", "*流入时间"))
        self.ob_timeInCol.setText(_translate("MainWindow", "2"))
        self.label_61.setText(_translate("MainWindow", "订单结构"))
        self.ob_channelCol.setText(_translate("MainWindow", "4"))
        self.ob_orderStructureCol.setText(_translate("MainWindow", "8"))
        self.label_64.setText(_translate("MainWindow", "服务渠道"))
        self.ob_platformCol.setText(_translate("MainWindow", "3"))
        self.label_63.setText(_translate("MainWindow", "平台"))
        self.groupBox_11.setTitle(_translate("MainWindow", "时间参数"))
        self.label_70.setText(_translate("MainWindow", "截单时间点"))
        self.label_69.setText(_translate("MainWindow", "订单流入日期"))
        self.ob_hourinCutoffHour.setText(_translate("MainWindow", "12"))
        self.groupBox_4.setTitle(_translate("MainWindow", "数据操作"))
        self.ob_dataProcess.setText(_translate("MainWindow", "数据处理"))
        self.ob_orderUpload.setText(_translate("MainWindow", "出库数据导入"))
        self.ob_orderTimeUpload.setText(_translate("MainWindow", "流入时间导入"))
        self.groupBox_5.setTitle(_translate("MainWindow", "出库数据参数设置"))
        self.label_21.setText(_translate("MainWindow", "*出库日期"))
        self.ob_dateCol.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "*订单号"))
        self.ob_orderCol.setText(_translate("MainWindow", "5"))
        self.label_22.setText(_translate("MainWindow", "*产品代码"))
        self.ob_skuCol.setText(_translate("MainWindow", "9"))
        self.label_24.setText(_translate("MainWindow", "*件   数"))
        self.label_42.setText(_translate("MainWindow", "*产品货型"))
        self.ob_skuSizeCol.setText(_translate("MainWindow", "10"))
        self.label_43.setText(_translate("MainWindow", "订单标识"))
        self.label_44.setText(_translate("MainWindow", "*上架时间"))
        self.ob_putawayDateCol.setText(_translate("MainWindow", "2"))
        self.ob_qtyCol.setText(_translate("MainWindow", "12"))
        self.ob_orderTagCol.setText(_translate("MainWindow", "4"))
        self.label_45.setText(_translate("MainWindow", "拣货单号"))
        self.ob_pickupNoCol.setText(_translate("MainWindow", "3"))
        self.label_46.setText(_translate("MainWindow", "库位代码"))
        self.ob_locationCol.setText(_translate("MainWindow", "8"))
        self.input_hint_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#ff0000;\">填写导入数据对应的列编号(从0开始）,&quot;*&quot;号标识的字段为必填项</span></p></body></html>"))
        self.groupBox_7.setTitle(_translate("MainWindow", "分析维度"))
        self.ob_platformAnalysis.setText(_translate("MainWindow", "平台分析"))
        self.ob_downloadAll.setText(_translate("MainWindow", "数据导出"))
        self.ob_clearAll.setText(_translate("MainWindow", "清理重置"))
        self.ob_EIQanalysis.setText(_translate("MainWindow", "EIQ分析"))
        self.ob_skuSale.setText(_translate("MainWindow", "SKU动销"))
        self.ob_customerSale.setText(_translate("MainWindow", "客户动销"))
        self.ob_multiOrder.setText(_translate("MainWindow", "多品订单组合分析"))
        self.ob_channelAnalysis.setText(_translate("MainWindow", "渠道分析"))
        self.ob_skuHourIn.setText(_translate("MainWindow", "SKU小时流入"))
        self.ob_ABCanalysis.setText(_translate("MainWindow", "ABC分析"))
        self.ob_orderAge.setText(_translate("MainWindow", "订单库龄分析"))
        self.ob_skuAge.setText(_translate("MainWindow", "SKU库龄分析"))
        self.groupBox_6.setTitle(_translate("MainWindow", "ABC参数设置"))
        self.ob_ABCfreq.setText(_translate("MainWindow", "0.5,0.2"))
        self.input_hint_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#ff0000;\">填写数字，以“,”分隔</span></p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "件数累计占比"))
        self.ob_ABCintervalDays.setText(_translate("MainWindow", "3,10"))
        self.label_35.setText(_translate("MainWindow", "出库频次占比"))
        self.label_27.setText(_translate("MainWindow", "出库间隔天数"))
        self.ob_ABCparameter.setText(_translate("MainWindow", "0.7,0.9,1.0"))
        self.ob_endDate.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_72.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">EndDate</span></p></body></html>"))
        self.ob_startDate.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_71.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">StartDate</span></p></body></html>"))
        self.ob_totalRow.setText(_translate("MainWindow", "0"))
        self.label_31.setText(_translate("MainWindow", "数据总行数"))
        self.label_29.setText(_translate("MainWindow", "异常数据"))
        self.ob_errorRow.setText(_translate("MainWindow", "0"))
        self.label_32.setText(_translate("MainWindow", "总订单数"))
        self.label_28.setText(_translate("MainWindow", "有效数据总行数"))
        self.ob_validRow.setText(_translate("MainWindow", "0"))
        self.ob_totalSKU.setText(_translate("MainWindow", "0"))
        self.label_25.setText(_translate("MainWindow", "总SKU数"))
        self.ob_totalDays.setText(_translate("MainWindow", "0"))
        self.label_26.setText(_translate("MainWindow", "出库天数"))
        self.ob_totalOrders.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#07387d;\">数据源预览</span></p></body></html>"))
        self.label_68.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#07387d;\">结果预览</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Outbound), _translate("MainWindow", "出库分析"))
        self.groupBox_8.setTitle(_translate("MainWindow", "数据操作"))
        self.ib_upload.setText(_translate("MainWindow", "入库数据导入"))
        self.ib_dataProcess.setText(_translate("MainWindow", "数据处理"))
        self.ib_clear.setText(_translate("MainWindow", "清理重置"))
        self.ib_download.setText(_translate("MainWindow", "数据导出"))
        self.ib_inboundAnalysis.setText(_translate("MainWindow", "入库量分析"))
        self.ib_cartonDistribution.setText(_translate("MainWindow", "箱数分布"))
        self.groupBox_12.setTitle(_translate("MainWindow", "时间参数设置"))
        self.label_76.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">StartDate</span></p></body></html>"))
        self.label_77.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">EndDate</span></p></body></html>"))
        self.label_78.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">（请输入要分析的时间段）</span></p></body></html>"))
        self.groupBox_10.setTitle(_translate("MainWindow", "入库数据设置"))
        self.ib_inboundTypeCol.setText(_translate("MainWindow", "11"))
        self.ib_inboundIdCol.setText(_translate("MainWindow", "8"))
        self.label_49.setText(_translate("MainWindow", "入库单号"))
        self.label_ib_receive_time.setText(_translate("MainWindow", "最早签收日期"))
        self.ib_receiveTimeCol.setText(_translate("MainWindow", "13"))
        self.label_54.setText(_translate("MainWindow", "海柜号"))
        self.ib_containerNoCol.setText(_translate("MainWindow", "22"))
        self.label_51.setText(_translate("MainWindow", "跟踪号"))
        self.ib_trackingNO.setText(_translate("MainWindow", "33"))
        self.label_74.setText(_translate("MainWindow", "货运方式"))
        self.label_53.setText(_translate("MainWindow", "入库单类型"))
        self.label_ib_date.setText(_translate("MainWindow", "收库日期"))
        self.ib_customerCol.setText(_translate("MainWindow", "17"))
        self.label_50.setText(_translate("MainWindow", "客户代码"))
        self.ib_dateCol.setText(_translate("MainWindow", "3"))
        self.ib_deliveryModeCol.setText(_translate("MainWindow", "4"))
        self.label_52.setText(_translate("MainWindow", "箱    号"))
        self.ib_warehouseCodeCol.setText(_translate("MainWindow", "25"))
        self.ib_cartonNoCol.setText(_translate("MainWindow", "29"))
        self.label_75.setText(_translate("MainWindow", "物理仓"))
        self.ib_skuSizeCol.setText(_translate("MainWindow", "32"))
        self.ib_skuCol.setText(_translate("MainWindow", "5"))
        self.label_56.setText(_translate("MainWindow", "产品货型"))
        self.label_55.setText(_translate("MainWindow", "产品代码"))
        self.label_57.setText(_translate("MainWindow", "收货数量"))
        self.ib_quantityCol.setText(_translate("MainWindow", "39"))
        self.label_58.setText(_translate("MainWindow", "收货体积"))
        self.ib_volCol.setText(_translate("MainWindow", "38"))
        self.input_hint_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#ff0000;\">*填写导入数据对应的列编号(从0开始）</span></p></body></html>"))
        self.ib_totalSKU.setText(_translate("MainWindow", "0"))
        self.label_39.setText(_translate("MainWindow", "总天数"))
        self.ib_totalRow.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "数据总行数"))
        self.ib_validRow.setText(_translate("MainWindow", "0"))
        self.ib_errorRow.setText(_translate("MainWindow", "0"))
        self.label_37.setText(_translate("MainWindow", "异常数据行数"))
        self.label_38.setText(_translate("MainWindow", "总SKU数"))
        self.label_36.setText(_translate("MainWindow", "有效数据总行数"))
        self.label_33.setText(_translate("MainWindow", "数据总列数"))
        self.ib_totalCol.setText(_translate("MainWindow", "0"))
        self.ib_totalDays.setText(_translate("MainWindow", "0"))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#07387d;\">数据源预览</span></p></body></html>"))
        self.label_73.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#07387d;\">结果预览</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Inbound), _translate("MainWindow", "入库分析"))

